<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace GPBMetadata;

class Demo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a0a64656d6f2e70726f746f120464656d6f222a0a0c48656c6c6f52657175657374120c0a046e616d65180120012809120c0a0461646472180220012809222b0a0a48656c6c6f5265706c79120f0a076d657373616765180120012809120c0a0464617461180220012809323e0a084772656574696e6712320a0853617948656c6c6f12122e64656d6f2e48656c6c6f526571756573741a102e64656d6f2e48656c6c6f5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

